git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
os:
  edit: 'zed -- {{filename}}'
  editAtLine: 'zed -- {{filename}}:{{line}}'
  editAtLineAndWait: 'zed --wait -- {{filename}}:{{line}}'
  openDirInEditor: 'zed -- {{dir}}'
gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
